

# THIS IS A PLACEHOLDER FILE. DO NOT USE IN THIS CONDITION!

set( SDL_GPU_LIBRARIES "/usr/lib/libSDL2_gpu.a" )
set( SDL_GPU_INCLUDE_DIRS "" )


mark_as_advanced(SDL_GPU_INCLUDE_DIR SDL_GPU_LIBRARY)
